version: '3.8'

services:
  # mongodb:
  #   image: mongo:6.0
  #   container_name: devvision-mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - devvision-network

  redis:
    image: redis:7.0
    container_name: devvision-redis
    ports:
      - "6379:6379"
    networks:
      - devvision-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: devvision-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - devvision-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: devvision-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - devvision-network

  api-gateway:
    image: nginx:alpine
    container_name: devvision-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - company-service
      - job-service
      - search-service
      - kafka
    networks:
      - devvision-network

  auth-service:
    build:
      context: .
      dockerfile: ./backend/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://devvision_user:Password123!@cluster0.4xyze1d.mongodb.net/auth-db?retryWrites=true&w=majority
      - REDIS_URI=redis://redis:6379
      - KAFKA_CLIENT_ID=auth-service
      - KAFKA_BROKERS=kafka:29092
      - JWT_SECRET=devvision_secret_key
    depends_on:
      - redis
      - kafka
    networks:
      - devvision-network

  company-service:
    build:
      context: .
      dockerfile: ./backend/company-service/Dockerfile
    container_name: company-service
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://devvision_user:Password123!@cluster0.4xyze1d.mongodb.net/company-db?retryWrites=true&w=majority
      - KAFKA_CLIENT_ID=company-service
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - devvision-network
    volumes:
      - company-uploads:/app/backend/company-service/uploads
    restart: always

  job-service:
    build:
      context: .
      dockerfile: ./backend/job-service/Dockerfile
    container_name: job-service
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://devvision_user:Password123!@cluster0.4xyze1d.mongodb.net/job-db?retryWrites=true&w=majority
      - KAFKA_CLIENT_ID=job-service
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - devvision-network

  search-service:
    build:
      context: .
      dockerfile: ./backend/search-service/Dockerfile
    container_name: search-service
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://devvision_user:Password123!@cluster0.4xyze1d.mongodb.net/search-db?retryWrites=true&w=majority
      - KAFKA_CLIENT_ID=search-service
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - devvision-network

networks:
  devvision-network:
    driver: bridge

volumes:
  mongo-data:
  company-uploads:
